// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Lattice from "../../../index.js";

export declare namespace EntitiesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * The Entities API
 */
export class EntitiesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<EntitiesClient.Options>;

    constructor(options: EntitiesClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Publish an entity for ingest into the Entities API. Entities created with this method are "owned" by the originator: other sources,
     * such as the UI, may not edit or delete these entities. The server validates entities at API call time and
     * returns an error if the entity is invalid.
     *
     * An entity ID must be provided when calling this endpoint. If the entity referenced by the entity ID does not exist
     * then it will be created. Otherwise the entity will be updated. An entity will only be updated if its
     * provenance.sourceUpdateTime is greater than the provenance.sourceUpdateTime of the existing entity.
     *
     * @param {Lattice.Entity} request
     * @param {EntitiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Lattice.BadRequestError}
     * @throws {@link Lattice.UnauthorizedError}
     *
     * @example
     *     await client.entities.publishEntity({})
     */
    public publishEntity(
        request: Lattice.Entity,
        requestOptions?: EntitiesClient.RequestOptions,
    ): core.HttpResponsePromise<Lattice.Entity> {
        return core.HttpResponsePromise.fromPromise(this.__publishEntity(request, requestOptions));
    }

    private async __publishEntity(
        request: Lattice.Entity,
        requestOptions?: EntitiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Lattice.Entity>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatticeEnvironment.Default,
                "api/v1/entities",
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Lattice.Entity, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Lattice.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Lattice.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.LatticeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/api/v1/entities");
    }

    /**
     * @param {Lattice.GetEntityRequest} request
     * @param {EntitiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Lattice.BadRequestError}
     * @throws {@link Lattice.UnauthorizedError}
     * @throws {@link Lattice.NotFoundError}
     *
     * @example
     *     await client.entities.getEntity({
     *         entityId: "entityId"
     *     })
     */
    public getEntity(
        request: Lattice.GetEntityRequest,
        requestOptions?: EntitiesClient.RequestOptions,
    ): core.HttpResponsePromise<Lattice.Entity> {
        return core.HttpResponsePromise.fromPromise(this.__getEntity(request, requestOptions));
    }

    private async __getEntity(
        request: Lattice.GetEntityRequest,
        requestOptions?: EntitiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Lattice.Entity>> {
        const { entityId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatticeEnvironment.Default,
                `api/v1/entities/${core.url.encodePathParam(entityId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Lattice.Entity, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Lattice.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Lattice.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Lattice.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.LatticeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/entities/{entityId}");
    }

    /**
     * Only fields marked with overridable can be overridden. Please refer to our documentation to see the comprehensive
     * list of fields that can be overridden. The entity in the request body should only have a value set on the field
     * specified in the field path parameter. Field paths are rooted in the base entity object and must be represented
     * using lower_snake_case. Do not include "entity" in the field path.
     *
     * Note that overrides are applied in an eventually consistent manner. If multiple overrides are created
     * concurrently for the same field path, the last writer wins.
     *
     * @param {Lattice.EntityOverride} request
     * @param {EntitiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Lattice.BadRequestError}
     * @throws {@link Lattice.UnauthorizedError}
     * @throws {@link Lattice.NotFoundError}
     *
     * @example
     *     await client.entities.overrideEntity({
     *         entityId: "entityId",
     *         fieldPath: "mil_view.disposition"
     *     })
     */
    public overrideEntity(
        request: Lattice.EntityOverride,
        requestOptions?: EntitiesClient.RequestOptions,
    ): core.HttpResponsePromise<Lattice.Entity> {
        return core.HttpResponsePromise.fromPromise(this.__overrideEntity(request, requestOptions));
    }

    private async __overrideEntity(
        request: Lattice.EntityOverride,
        requestOptions?: EntitiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Lattice.Entity>> {
        const { entityId, fieldPath, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatticeEnvironment.Default,
                `api/v1/entities/${core.url.encodePathParam(entityId)}/override/${core.url.encodePathParam(fieldPath)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Lattice.Entity, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Lattice.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Lattice.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Lattice.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.LatticeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/api/v1/entities/{entityId}/override/{fieldPath}",
        );
    }

    /**
     * This operation clears the override value from the specified field path on the entity.
     *
     * @param {Lattice.RemoveEntityOverrideRequest} request
     * @param {EntitiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Lattice.BadRequestError}
     * @throws {@link Lattice.UnauthorizedError}
     * @throws {@link Lattice.NotFoundError}
     *
     * @example
     *     await client.entities.removeEntityOverride({
     *         entityId: "entityId",
     *         fieldPath: "mil_view.disposition"
     *     })
     */
    public removeEntityOverride(
        request: Lattice.RemoveEntityOverrideRequest,
        requestOptions?: EntitiesClient.RequestOptions,
    ): core.HttpResponsePromise<Lattice.Entity> {
        return core.HttpResponsePromise.fromPromise(this.__removeEntityOverride(request, requestOptions));
    }

    private async __removeEntityOverride(
        request: Lattice.RemoveEntityOverrideRequest,
        requestOptions?: EntitiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Lattice.Entity>> {
        const { entityId, fieldPath } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatticeEnvironment.Default,
                `api/v1/entities/${core.url.encodePathParam(entityId)}/override/${core.url.encodePathParam(fieldPath)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Lattice.Entity, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Lattice.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Lattice.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Lattice.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.LatticeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v1/entities/{entityId}/override/{fieldPath}",
        );
    }

    /**
     * This is a long polling API that will first return all pre-existing data and then return all new data as
     * it becomes available. If you want to start a new polling session then open a request with an empty
     * 'sessionToken' in the request body. The server will return a new session token in the response.
     * If you want to retrieve the next batch of results from an existing polling session then send the session
     * token you received from the server in the request body. If no new data is available then the server will
     * hold the connection open for up to 5 minutes. After the 5 minute timeout period, the server will close the
     * connection with no results and you may resume polling with the same session token. If your session falls behind
     * more than 3x the total number of entities in the environment, the server will terminate your session.
     * In this case you must start a new session by sending a request with an empty session token.
     *
     * @param {Lattice.EntityEventRequest} request
     * @param {EntitiesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Lattice.BadRequestError}
     * @throws {@link Lattice.UnauthorizedError}
     * @throws {@link Lattice.NotFoundError}
     * @throws {@link Lattice.RequestTimeoutError}
     * @throws {@link Lattice.TooManyRequestsError}
     *
     * @example
     *     await client.entities.longPollEntityEvents({
     *         sessionToken: "sessionToken"
     *     })
     */
    public longPollEntityEvents(
        request: Lattice.EntityEventRequest,
        requestOptions?: EntitiesClient.RequestOptions,
    ): core.HttpResponsePromise<Lattice.EntityEventResponse> {
        return core.HttpResponsePromise.fromPromise(this.__longPollEntityEvents(request, requestOptions));
    }

    private async __longPollEntityEvents(
        request: Lattice.EntityEventRequest,
        requestOptions?: EntitiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Lattice.EntityEventResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatticeEnvironment.Default,
                "api/v1/entities/events",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Lattice.EntityEventResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Lattice.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Lattice.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Lattice.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 408:
                    throw new Lattice.RequestTimeoutError(
                        _response.error.body as Lattice.entity.Error_,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Lattice.TooManyRequestsError(
                        _response.error.body as Lattice.entity.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.LatticeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/v1/entities/events");
    }

    /**
     * @beta This endpoint is in pre-release and may change.
     *
     * Establishes a server-sent events (SSE) connection that streams entity data in real-time.
     * This is a one-way connection from server to client that follows the SSE protocol with text/event-stream content type.
     *
     * This endpoint enables clients to maintain a real-time view of the common operational picture (COP)
     * by first streaming all pre-existing entities that match filter criteria, then continuously delivering
     * updates as entities are created, modified, or deleted.
     *
     * The server first sends events with type PREEXISTING for all live entities matching the filter that existed before the stream was open,
     * then streams CREATE events for newly created entities, UPDATE events when existing entities change, and DELETED events when entities are removed. The stream remains open
     * indefinitely unless preExistingOnly is set to true.
     *
     * Heartbeat messages can be configured to maintain connection health and detect disconnects by setting the heartbeatIntervalMS
     * parameter. These heartbeats help keep the connection alive and allow clients to verify the server is still responsive.
     *
     * Clients can optimize bandwidth usage by specifying which entity components they need populated using the componentsToInclude parameter.
     * This allows receiving only relevant data instead of complete entities.
     *
     * The connection automatically recovers from temporary disconnections, resuming the stream where it left off. Unlike polling approaches,
     * this provides real-time updates with minimal latency and reduced server load.
     */
    public streamEntities(
        request: Lattice.EntityStreamRequest = {},
        requestOptions?: EntitiesClient.RequestOptions,
    ): core.HttpResponsePromise<core.Stream<Lattice.StreamEntitiesResponse>> {
        return core.HttpResponsePromise.fromPromise(this.__streamEntities(request, requestOptions));
    }

    private async __streamEntities(
        request: Lattice.EntityStreamRequest = {},
        requestOptions?: EntitiesClient.RequestOptions,
    ): Promise<core.WithRawResponse<core.Stream<Lattice.StreamEntitiesResponse>>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher<ReadableStream>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatticeEnvironment.Default,
                "api/v1/entities/stream",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            responseType: "sse",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: new core.Stream({
                    stream: _response.body,
                    parse: (data) => data as any,
                    signal: requestOptions?.abortSignal,
                    eventShape: {
                        type: "sse",
                    },
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Lattice.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Lattice.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.LatticeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/v1/entities/stream");
    }
}
