// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface AgentStreamRequest {
    /** The selector criteria to determine which tasks the agent receives. */
    agentSelector?: Lattice.EntityIdsSelector;
    /** The time interval, defined in seconds, that determines the frequency at which to send heartbeat events. Defaults to 30s. */
    heartbeatIntervalMs?: number;
}
