// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface TaskQuery {
    /** If set, returns results starting from the given pageToken. */
    pageToken?: string;
    /**
     * If present matches Tasks with this parent Task ID.
     * Note: this is mutually exclusive with all other query parameters, for example, either provide parent task ID, or
     * any of the remaining parameters, but not both.
     */
    parentTaskId?: string;
    statusFilter?: TaskQuery.StatusFilter;
    /** If provided, only provides Tasks updated within the time range. */
    updateTimeRange?: TaskQuery.UpdateTimeRange;
}

export namespace TaskQuery {
    export interface StatusFilter {
        /** Status of the Task to filter by, inclusive. */
        status?: StatusFilter.Status | undefined;
    }

    export namespace StatusFilter {
        /** Status of the Task to filter by, inclusive. */
        export const Status = {
            StatusInvalid: "STATUS_INVALID",
            StatusCreated: "STATUS_CREATED",
            StatusScheduledInManager: "STATUS_SCHEDULED_IN_MANAGER",
            StatusSent: "STATUS_SENT",
            StatusMachineReceipt: "STATUS_MACHINE_RECEIPT",
            StatusAck: "STATUS_ACK",
            StatusWilco: "STATUS_WILCO",
            StatusExecuting: "STATUS_EXECUTING",
            StatusWaitingForUpdate: "STATUS_WAITING_FOR_UPDATE",
            StatusDoneOk: "STATUS_DONE_OK",
            StatusDoneNotOk: "STATUS_DONE_NOT_OK",
            StatusReplaced: "STATUS_REPLACED",
            StatusCancelRequested: "STATUS_CANCEL_REQUESTED",
            StatusCompleteRequested: "STATUS_COMPLETE_REQUESTED",
            StatusVersionRejected: "STATUS_VERSION_REJECTED",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
    }

    /**
     * If provided, only provides Tasks updated within the time range.
     */
    export interface UpdateTimeRange {
        /** If provided, returns Tasks only updated after this time. */
        startTime?: string | undefined;
        /** If provided, returns Tasks only updated before this time. */
        endTime?: string | undefined;
    }
}
