// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface TaskStreamRequest {
    /** The time interval, in milliseconds, that determines the frequency at which to send heartbeat events. Defaults to 30000 (30 seconds). */
    heartbeatIntervalMs?: number;
    /**
     * The time interval, in milliseconds, after an update for a given task before another one will be sent for the same task.
     * If set, value must be >= 250.
     */
    rateLimit?: number;
    /**
     * Optional flag to only include tasks created or updated after the stream is initiated, and not any previous preexisting tasks.
     * If unset or false, the stream will include any new tasks and task updates, as well as all preexisting tasks.
     */
    excludePreexistingTasks?: boolean;
    /** Optional filter that only returns tasks with specific types. If not provided, all task types will be streamed. */
    taskType?: TaskStreamRequest.TaskType;
}

export namespace TaskStreamRequest {
    /**
     * Optional filter that only returns tasks with specific types. If not provided, all task types will be streamed.
     */
    export type TaskType =
        | {
              taskTypeUrls: string[];
          }
        | {
              taskTypePrefix: string;
          };
}
