// This file was auto-generated by Fern from our API Definition.

export interface AcmDetails {
    acmType?: AcmDetails.AcmType | undefined;
    /**
     * Used for loosely typed associations, such as assignment to a specific fires unit.
     *  Limit to 150 characters.
     */
    acmDescription?: string | undefined;
}

export namespace AcmDetails {
    export const AcmType = {
        AcmDetailTypeInvalid: "ACM_DETAIL_TYPE_INVALID",
        AcmDetailTypeLandingZone: "ACM_DETAIL_TYPE_LANDING_ZONE",
    } as const;
    export type AcmType = (typeof AcmType)[keyof typeof AcmType];
}
