// This file was auto-generated by Fern from our API Definition.

/**
 * Represents an agent capable of processing tasks.
 */
export interface Agent {
    /** Entity ID of the agent. */
    entityId?: string | undefined;
}
