// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Allocation contains a list of agents allocated to a task.
 */
export interface Allocation {
    /** Agents actively being utilized in a task. */
    activeAgents?: Lattice.Agent[] | undefined;
}
