// This file was auto-generated by Fern from our API Definition.

/**
 * An alternate id for an Entity.
 */
export interface AlternateId {
    id?: string | undefined;
    type?: AlternateId.Type | undefined;
}

export namespace AlternateId {
    export const Type = {
        AltIdTypeInvalid: "ALT_ID_TYPE_INVALID",
        AltIdTypeTrackId2: "ALT_ID_TYPE_TRACK_ID_2",
        AltIdTypeTrackId1: "ALT_ID_TYPE_TRACK_ID_1",
        AltIdTypeSpiId: "ALT_ID_TYPE_SPI_ID",
        AltIdTypeNitfFileTitle: "ALT_ID_TYPE_NITF_FILE_TITLE",
        AltIdTypeTrackRepoAlertId: "ALT_ID_TYPE_TRACK_REPO_ALERT_ID",
        AltIdTypeAssetId: "ALT_ID_TYPE_ASSET_ID",
        AltIdTypeLink16TrackNumber: "ALT_ID_TYPE_LINK16_TRACK_NUMBER",
        AltIdTypeLink16Ju: "ALT_ID_TYPE_LINK16_JU",
        AltIdTypeNcctMessageId: "ALT_ID_TYPE_NCCT_MESSAGE_ID",
        AltIdTypeCallsign: "ALT_ID_TYPE_CALLSIGN",
        AltIdTypeMmsiId: "ALT_ID_TYPE_MMSI_ID",
        AltIdTypeVmfUrn: "ALT_ID_TYPE_VMF_URN",
        AltIdTypeImoId: "ALT_ID_TYPE_IMO_ID",
        AltIdTypeVmfTargetNumber: "ALT_ID_TYPE_VMF_TARGET_NUMBER",
        AltIdTypeSerialNumber: "ALT_ID_TYPE_SERIAL_NUMBER",
        AltIdTypeRegistrationId: "ALT_ID_TYPE_REGISTRATION_ID",
        AltIdTypeIbsGid: "ALT_ID_TYPE_IBS_GID",
        AltIdTypeDodaac: "ALT_ID_TYPE_DODAAC",
        AltIdTypeUic: "ALT_ID_TYPE_UIC",
        AltIdTypeNoradCatId: "ALT_ID_TYPE_NORAD_CAT_ID",
        AltIdTypeUnoosaName: "ALT_ID_TYPE_UNOOSA_NAME",
        AltIdTypeUnoosaId: "ALT_ID_TYPE_UNOOSA_ID",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
