// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * The direction from which the signal is received
 */
export interface AngleOfArrival {
    /**
     * Origin (LLA) and attitude (relative to ENU) of a ray pointing towards the detection. The attitude represents a
     *  forward-left-up (FLU) frame where the x-axis (1, 0, 0) is pointing towards the target.
     */
    relativePose?: Lattice.Pose | undefined;
    /**
     * Bearing/elevation covariance matrix where bearing is defined in radians CCW+ about the z-axis from the x-axis of FLU frame
     *  and elevation is positive down from the FL/XY plane.
     *  mxx = bearing variance in rad^2
     *  mxy = bearing/elevation covariance in rad^2
     *  myy = elevation variance in rad^2
     */
    bearingElevationCovarianceRad2?: Lattice.TMat2 | undefined;
}
