// This file was auto-generated by Fern from our API Definition.

/**
 * Represents all of the necessary information required to generate a summarized
 *  classification marking.
 *
 *  > example: A summarized classification marking of "TOPSECRET//NOFORN//FISA"
 *             would be defined as: { "level": 5, "caveats": [ "NOFORN, "FISA" ] }
 */
export interface ClassificationInformation {
    /** Classification level to be applied to the information in question. */
    level?: ClassificationInformation.Level | undefined;
    /** Caveats that may further restrict how the information can be disseminated. */
    caveats?: string[] | undefined;
}

export namespace ClassificationInformation {
    /** Classification level to be applied to the information in question. */
    export const Level = {
        ClassificationLevelsInvalid: "CLASSIFICATION_LEVELS_INVALID",
        ClassificationLevelsUnclassified: "CLASSIFICATION_LEVELS_UNCLASSIFIED",
        ClassificationLevelsControlledUnclassified: "CLASSIFICATION_LEVELS_CONTROLLED_UNCLASSIFIED",
        ClassificationLevelsConfidential: "CLASSIFICATION_LEVELS_CONFIDENTIAL",
        ClassificationLevelsSecret: "CLASSIFICATION_LEVELS_SECRET",
        ClassificationLevelsTopSecret: "CLASSIFICATION_LEVELS_TOP_SECRET",
    } as const;
    export type Level = (typeof Level)[keyof typeof Level];
}
