// This file was auto-generated by Fern from our API Definition.

/**
 * A message describing the component's health status.
 */
export interface ComponentMessage {
    /** The status associated with this message. */
    status?: ComponentMessage.Status | undefined;
    /** The human-readable content of the message. */
    message?: string | undefined;
}

export namespace ComponentMessage {
    /** The status associated with this message. */
    export const Status = {
        HealthStatusInvalid: "HEALTH_STATUS_INVALID",
        HealthStatusHealthy: "HEALTH_STATUS_HEALTHY",
        HealthStatusWarn: "HEALTH_STATUS_WARN",
        HealthStatusFail: "HEALTH_STATUS_FAIL",
        HealthStatusOffline: "HEALTH_STATUS_OFFLINE",
        HealthStatusNotReady: "HEALTH_STATUS_NOT_READY",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
