// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

export interface DecorrelatedAll {
    /** Metadata about the decorrelation. */
    metadata?: Lattice.CorrelationMetadata | undefined;
}
