// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Defines the current state of a task's delivery.
 */
export interface DeliveryState {
    /** The current status of the delivery. */
    status?: DeliveryState.Status | undefined;
    /** Errors associated with the delivery, if any. */
    error?: Lattice.DeliveryError | undefined;
    /** Optional scheduling constraints for Lattice delivery of the task. */
    deliveryConstraints?: Lattice.DeliveryConstraints | undefined;
}

export namespace DeliveryState {
    /** The current status of the delivery. */
    export const Status = {
        DeliveryStatusInvalid: "DELIVERY_STATUS_INVALID",
        DeliveryStatusDelivered: "DELIVERY_STATUS_DELIVERED",
        DeliveryStatusPendingExecute: "DELIVERY_STATUS_PENDING_EXECUTE",
        DeliveryStatusPendingCancel: "DELIVERY_STATUS_PENDING_CANCEL",
        DeliveryStatusPendingComplete: "DELIVERY_STATUS_PENDING_COMPLETE",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
