// This file was auto-generated by Fern from our API Definition.

/**
 * Describes a Echelon group type.  Comprised of entities which are members of the
 *  same unit or echelon. Ex: A group of tanks within a armored company or that same company
 *  as a member of a battalion.
 */
export interface Echelon {
    armyEchelon?: Echelon.ArmyEchelon | undefined;
}

export namespace Echelon {
    export const ArmyEchelon = {
        ArmyEchelonInvalid: "ARMY_ECHELON_INVALID",
        ArmyEchelonFireTeam: "ARMY_ECHELON_FIRE_TEAM",
        ArmyEchelonSquad: "ARMY_ECHELON_SQUAD",
        ArmyEchelonPlatoon: "ARMY_ECHELON_PLATOON",
        ArmyEchelonCompany: "ARMY_ECHELON_COMPANY",
        ArmyEchelonBattalion: "ARMY_ECHELON_BATTALION",
        ArmyEchelonRegiment: "ARMY_ECHELON_REGIMENT",
        ArmyEchelonBrigade: "ARMY_ECHELON_BRIGADE",
        ArmyEchelonDivision: "ARMY_ECHELON_DIVISION",
        ArmyEchelonCorps: "ARMY_ECHELON_CORPS",
        ArmyEchelonArmy: "ARMY_ECHELON_ARMY",
    } as const;
    export type ArmyEchelon = (typeof ArmyEchelon)[keyof typeof ArmyEchelon];
}
