// This file was auto-generated by Fern from our API Definition.

/**
 * A representation of a single emitter notation.
 */
export interface EmitterNotation {
    emitterNotation?: string | undefined;
    /** confidence as a percentage that the emitter notation in this component is accurate */
    confidence?: number | undefined;
}
