// This file was auto-generated by Fern from our API Definition.

/**
 * Indicates ellipse characteristics and probability that an entity lies within the defined ellipse.
 */
export interface ErrorEllipse {
    /** Defines the probability in percentage that an entity lies within the given ellipse: 0-1. */
    probability?: number | undefined;
    /** Defines the distance from the center point of the ellipse to the furthest distance on the perimeter in meters. */
    semiMajorAxisM?: number | undefined;
    /** Defines the distance from the center point of the ellipse to the shortest distance on the perimeter in meters. */
    semiMinorAxisM?: number | undefined;
    /** The orientation of the semi-major relative to true north in degrees from clockwise: 0-180 due to symmetry across the semi-minor axis. */
    orientationD?: number | undefined;
}
