// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * A field specific classification information definition.
 */
export interface FieldClassificationInformation {
    /**
     * Proto field path which is the string representation of a field.
     *  > example: signal.bandwidth_hz would be bandwidth_hz in the signal component
     */
    fieldPath?: string | undefined;
    /** The information which makes up the field level classification marking. */
    classificationInformation?: Lattice.ClassificationInformation | undefined;
}
