// This file was auto-generated by Fern from our API Definition.

/**
 * Defaults to an interval of 5 seconds. If the DeliverBefore field in the task's DeliveryConstraints isn't populated, Lattice does not retry delivery and instead logs a warning.
 */
export interface FixedRetry {
    /** Specifies the interval between retries. A default interval of 5 seconds is used if this field is not set. */
    retryInterval?: string | undefined;
}
