// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * A component to represent a frequency range.
 */
export interface FrequencyRange {
    /** Indicates the lowest measured frequency of a signal (Hz). */
    minimumFrequencyHz?: Lattice.Frequency | undefined;
    /** Indicates the maximum measured frequency of a signal (Hz). */
    maximumFrequencyHz?: Lattice.Frequency | undefined;
}
