// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * A component for describing frequency.
 */
export interface Frequency {
    /** Indicates a frequency of a signal (Hz) with its standard deviation. */
    frequencyHz?: Lattice.Measurement | undefined;
}
