// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Fuel describes an entity's repository of fuels stores including current amount, operational requirements, and maximum authorized capacity
 */
export interface Fuel {
    /** Unique fuel identifier */
    fuelId?: string | undefined;
    /** Long form name of the fuel source. */
    name?: string | undefined;
    /** Timestamp the information was reported */
    reportedDate?: string | undefined;
    /** Amount of gallons on hand */
    amountGallons?: number | undefined;
    /** How much the asset is allowed to have available (in gallons) */
    maxAuthorizedCapacityGallons?: number | undefined;
    /** Minimum required for operations (in gallons) */
    operationalRequirementGallons?: number | undefined;
    /**
     * Fuel in a single asset may have different levels of classification
     *  Use case: fuel for a SECRET asset while diesel fuel may be UNCLASSIFIED
     */
    dataClassification?: Lattice.Classification | undefined;
    /** Source of information */
    dataSource?: string | undefined;
}
