// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * A point shaped geo-entity.
 *  See https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.2
 */
export interface GeoPoint {
    position?: Lattice.Position | undefined;
}
