// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * A component that describes the shape of a geo-entity.
 */
export interface GeoShape {
    point?: Lattice.GeoPoint | undefined;
    line?: Lattice.GeoLine | undefined;
    polygon?: Lattice.GeoPolygon | undefined;
    ellipse?: Lattice.GeoEllipse | undefined;
    ellipsoid?: Lattice.GeoEllipsoid | undefined;
}
