// This file was auto-generated by Fern from our API Definition.

export interface HeartbeatObject {
    /** The timestamp at which the heartbeat message was sent. */
    timestamp?: string | undefined;
}
