// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * A closed ring of points. The first and last point must be the same.
 */
export interface LinearRing {
    positions?: Lattice.GeoPolygonPosition[] | undefined;
}
