// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * A line of bearing of a signal.
 */
export interface LineOfBearing {
    /** The direction pointing from this entity to the detection */
    angleOfArrival?: Lattice.AngleOfArrival | undefined;
    /** The estimated distance of the detection */
    rangeEstimateM?: Lattice.Measurement | undefined;
    /** The maximum distance of the detection */
    maxRangeM?: Lattice.Measurement | undefined;
}
