// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

export interface ListResponse {
    path_metadatas: Lattice.PathMetadata[];
    next_page_token?: string | undefined;
}
