// This file was auto-generated by Fern from our API Definition.

export interface MediaItem {
    type?: MediaItem.Type | undefined;
    /** The path, relative to the environment base URL, where media related to an entity can be accessed */
    relativePath?: string | undefined;
}

export namespace MediaItem {
    export const Type = {
        MediaTypeInvalid: "MEDIA_TYPE_INVALID",
        MediaTypeImage: "MEDIA_TYPE_IMAGE",
        MediaTypeVideo: "MEDIA_TYPE_VIDEO",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
