// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Media associated with an entity.
 */
export interface Media {
    media?: Lattice.MediaItem[] | undefined;
}
