//  This file was auto-generated from our API Definition.

/**
 * Provides the disposition, environment, and nationality of an Entity.
 */
export interface MilView {
    disposition?: MilView.Disposition | undefined;
    environment?: MilView.Environment | undefined;
    nationality?: MilView.Nationality | undefined;
}

export namespace MilView {
    export const Disposition = {
        DispositionUnknown: "DISPOSITION_UNKNOWN",
        DispositionFriendly: "DISPOSITION_FRIENDLY",
        DispositionHostile: "DISPOSITION_HOSTILE",
        DispositionSuspicious: "DISPOSITION_SUSPICIOUS",
        DispositionAssumedFriendly: "DISPOSITION_ASSUMED_FRIENDLY",
        DispositionNeutral: "DISPOSITION_NEUTRAL",
        DispositionPending: "DISPOSITION_PENDING",
    } as const;
    export type Disposition = (typeof Disposition)[keyof typeof Disposition];
    export const Environment = {
        EnvironmentUnknown: "ENVIRONMENT_UNKNOWN",
        EnvironmentAir: "ENVIRONMENT_AIR",
        EnvironmentSurface: "ENVIRONMENT_SURFACE",
        EnvironmentSubSurface: "ENVIRONMENT_SUB_SURFACE",
        EnvironmentLand: "ENVIRONMENT_LAND",
        EnvironmentSpace: "ENVIRONMENT_SPACE",
    } as const;
    export type Environment = (typeof Environment)[keyof typeof Environment];
    export const Nationality = {
        NationalityInvalid: "NATIONALITY_INVALID",
        NationalityAlbania: "NATIONALITY_ALBANIA",
        NationalityAlgeria: "NATIONALITY_ALGERIA",
        NationalityArgentina: "NATIONALITY_ARGENTINA",
        NationalityArmenia: "NATIONALITY_ARMENIA",
        NationalityAustralia: "NATIONALITY_AUSTRALIA",
        NationalityAustria: "NATIONALITY_AUSTRIA",
        NationalityAzerbaijan: "NATIONALITY_AZERBAIJAN",
        NationalityBelarus: "NATIONALITY_BELARUS",
        NationalityBelgium: "NATIONALITY_BELGIUM",
        NationalityBolivia: "NATIONALITY_BOLIVIA",
        NationalityBosniaAndHerzegovina: "NATIONALITY_BOSNIA_AND_HERZEGOVINA",
        NationalityBrazil: "NATIONALITY_BRAZIL",
        NationalityBulgaria: "NATIONALITY_BULGARIA",
        NationalityCambodia: "NATIONALITY_CAMBODIA",
        NationalityCanada: "NATIONALITY_CANADA",
        NationalityChile: "NATIONALITY_CHILE",
        NationalityChina: "NATIONALITY_CHINA",
        NationalityColombia: "NATIONALITY_COLOMBIA",
        NationalityCroatia: "NATIONALITY_CROATIA",
        NationalityCuba: "NATIONALITY_CUBA",
        NationalityCyprus: "NATIONALITY_CYPRUS",
        NationalityCzechRepublic: "NATIONALITY_CZECH_REPUBLIC",
        NationalityDemocraticPeoplesRepublicOfKorea: "NATIONALITY_DEMOCRATIC_PEOPLES_REPUBLIC_OF_KOREA",
        NationalityDenmark: "NATIONALITY_DENMARK",
        NationalityDominicanRepublic: "NATIONALITY_DOMINICAN_REPUBLIC",
        NationalityEcuador: "NATIONALITY_ECUADOR",
        NationalityEgypt: "NATIONALITY_EGYPT",
        NationalityEstonia: "NATIONALITY_ESTONIA",
        NationalityEthiopia: "NATIONALITY_ETHIOPIA",
        NationalityFinland: "NATIONALITY_FINLAND",
        NationalityFrance: "NATIONALITY_FRANCE",
        NationalityGeorgia: "NATIONALITY_GEORGIA",
        NationalityGermany: "NATIONALITY_GERMANY",
        NationalityGreece: "NATIONALITY_GREECE",
        NationalityGuatemala: "NATIONALITY_GUATEMALA",
        NationalityGuinea: "NATIONALITY_GUINEA",
        NationalityHungary: "NATIONALITY_HUNGARY",
        NationalityIceland: "NATIONALITY_ICELAND",
        NationalityIndia: "NATIONALITY_INDIA",
        NationalityIndonesia: "NATIONALITY_INDONESIA",
        NationalityInternationalRedCross: "NATIONALITY_INTERNATIONAL_RED_CROSS",
        NationalityIraq: "NATIONALITY_IRAQ",
        NationalityIreland: "NATIONALITY_IRELAND",
        NationalityIslamicRepublicOfIran: "NATIONALITY_ISLAMIC_REPUBLIC_OF_IRAN",
        NationalityIsrael: "NATIONALITY_ISRAEL",
        NationalityItaly: "NATIONALITY_ITALY",
        NationalityJamaica: "NATIONALITY_JAMAICA",
        NationalityJapan: "NATIONALITY_JAPAN",
        NationalityJordan: "NATIONALITY_JORDAN",
        NationalityKazakhstan: "NATIONALITY_KAZAKHSTAN",
        NationalityKuwait: "NATIONALITY_KUWAIT",
        NationalityKyrghyzRepublic: "NATIONALITY_KYRGHYZ_REPUBLIC",
        NationalityLaoPeoplesDemocraticRepublic: "NATIONALITY_LAO_PEOPLES_DEMOCRATIC_REPUBLIC",
        NationalityLatvia: "NATIONALITY_LATVIA",
        NationalityLebanon: "NATIONALITY_LEBANON",
        NationalityLiberia: "NATIONALITY_LIBERIA",
        NationalityLithuania: "NATIONALITY_LITHUANIA",
        NationalityLuxembourg: "NATIONALITY_LUXEMBOURG",
        NationalityMadagascar: "NATIONALITY_MADAGASCAR",
        NationalityMalaysia: "NATIONALITY_MALAYSIA",
        NationalityMalta: "NATIONALITY_MALTA",
        NationalityMexico: "NATIONALITY_MEXICO",
        NationalityMoldova: "NATIONALITY_MOLDOVA",
        NationalityMontenegro: "NATIONALITY_MONTENEGRO",
        NationalityMorocco: "NATIONALITY_MOROCCO",
        NationalityMyanmar: "NATIONALITY_MYANMAR",
        NationalityNato: "NATIONALITY_NATO",
        NationalityNetherlands: "NATIONALITY_NETHERLANDS",
        NationalityNewZealand: "NATIONALITY_NEW_ZEALAND",
        NationalityNicaragua: "NATIONALITY_NICARAGUA",
        NationalityNigeria: "NATIONALITY_NIGERIA",
        NationalityNorway: "NATIONALITY_NORWAY",
        NationalityPakistan: "NATIONALITY_PAKISTAN",
        NationalityPanama: "NATIONALITY_PANAMA",
        NationalityParaguay: "NATIONALITY_PARAGUAY",
        NationalityPeru: "NATIONALITY_PERU",
        NationalityPhilippines: "NATIONALITY_PHILIPPINES",
        NationalityPoland: "NATIONALITY_POLAND",
        NationalityPortugal: "NATIONALITY_PORTUGAL",
        NationalityRepublicOfKorea: "NATIONALITY_REPUBLIC_OF_KOREA",
        NationalityRomania: "NATIONALITY_ROMANIA",
        NationalityRussia: "NATIONALITY_RUSSIA",
        NationalitySaudiArabia: "NATIONALITY_SAUDI_ARABIA",
        NationalitySenegal: "NATIONALITY_SENEGAL",
        NationalitySerbia: "NATIONALITY_SERBIA",
        NationalitySingapore: "NATIONALITY_SINGAPORE",
        NationalitySlovakia: "NATIONALITY_SLOVAKIA",
        NationalitySlovenia: "NATIONALITY_SLOVENIA",
        NationalitySouthAfrica: "NATIONALITY_SOUTH_AFRICA",
        NationalitySpain: "NATIONALITY_SPAIN",
        NationalitySudan: "NATIONALITY_SUDAN",
        NationalitySweden: "NATIONALITY_SWEDEN",
        NationalitySwitzerland: "NATIONALITY_SWITZERLAND",
        NationalitySyrianArabRepublic: "NATIONALITY_SYRIAN_ARAB_REPUBLIC",
        NationalityTaiwan: "NATIONALITY_TAIWAN",
        NationalityTajikistan: "NATIONALITY_TAJIKISTAN",
        NationalityThailand: "NATIONALITY_THAILAND",
        NationalityTheFormerYugoslavRepublicOfMacedonia: "NATIONALITY_THE_FORMER_YUGOSLAV_REPUBLIC_OF_MACEDONIA",
        NationalityTunisia: "NATIONALITY_TUNISIA",
        NationalityTurkey: "NATIONALITY_TURKEY",
        NationalityTurkmenistan: "NATIONALITY_TURKMENISTAN",
        NationalityUganda: "NATIONALITY_UGANDA",
        NationalityUkraine: "NATIONALITY_UKRAINE",
        NationalityUnitedKingdom: "NATIONALITY_UNITED_KINGDOM",
        NationalityUnitedNations: "NATIONALITY_UNITED_NATIONS",
        NationalityUnitedRepublicOfTanzania: "NATIONALITY_UNITED_REPUBLIC_OF_TANZANIA",
        NationalityUnitedStatesOfAmerica: "NATIONALITY_UNITED_STATES_OF_AMERICA",
        NationalityUruguay: "NATIONALITY_URUGUAY",
        NationalityUzbekistan: "NATIONALITY_UZBEKISTAN",
        NationalityVenezuela: "NATIONALITY_VENEZUELA",
        NationalityVietnam: "NATIONALITY_VIETNAM",
        NationalityYemen: "NATIONALITY_YEMEN",
        NationalityZimbabwe: "NATIONALITY_ZIMBABWE",
    } as const;
    export type Nationality = (typeof Nationality)[keyof typeof Nationality];
}
