// This file was auto-generated by Fern from our API Definition.

/**
 * Describes the Mode 5 transponder interrogation status and codes.
 */
export interface Mode5 {
    /** The validity of the response from the Mode 5 interrogation. */
    mode5InterrogationResponse?: Mode5.Mode5InterrogationResponse | undefined;
    /** The Mode 5 code assigned to military assets. */
    mode5?: number | undefined;
    /** The Mode 5 platform identification code. */
    mode5PlatformId?: number | undefined;
}

export namespace Mode5 {
    /** The validity of the response from the Mode 5 interrogation. */
    export const Mode5InterrogationResponse = {
        InterrogationResponseInvalid: "INTERROGATION_RESPONSE_INVALID",
        InterrogationResponseCorrect: "INTERROGATION_RESPONSE_CORRECT",
        InterrogationResponseIncorrect: "INTERROGATION_RESPONSE_INCORRECT",
        InterrogationResponseNoResponse: "INTERROGATION_RESPONSE_NO_RESPONSE",
    } as const;
    export type Mode5InterrogationResponse =
        (typeof Mode5InterrogationResponse)[keyof typeof Mode5InterrogationResponse];
}
