// This file was auto-generated by Fern from our API Definition.

/**
 * Munition describes an entity's munitions stores
 */
export interface Munition {
    /** Unique munition identifier */
    munitionId?: string | undefined;
    /** Long form name of the munition */
    name?: string | undefined;
    /** Number of units */
    quantityUnits?: number | undefined;
}
