// This file was auto-generated by Fern from our API Definition.

export interface OrbitMeanElementsMetadata {
    /** Creation date/time in UTC */
    creationDate?: string | undefined;
    /** Creating agency or operator */
    originator?: string | undefined;
    /** ID that uniquely identifies a message from a given originator. */
    messageId?: string | undefined;
    /** Reference frame, assumed to be Earth-centered */
    refFrame?: OrbitMeanElementsMetadata.RefFrame | undefined;
    /** Reference frame epoch in UTC - mandatory only if not intrinsic to frame definition */
    refFrameEpoch?: string | undefined;
    meanElementTheory?: OrbitMeanElementsMetadata.MeanElementTheory | undefined;
}

export namespace OrbitMeanElementsMetadata {
    /** Reference frame, assumed to be Earth-centered */
    export const RefFrame = {
        EciReferenceFrameInvalid: "ECI_REFERENCE_FRAME_INVALID",
        EciReferenceFrameTeme: "ECI_REFERENCE_FRAME_TEME",
    } as const;
    export type RefFrame = (typeof RefFrame)[keyof typeof RefFrame];
    export const MeanElementTheory = {
        MeanElementTheoryInvalid: "MEAN_ELEMENT_THEORY_INVALID",
        MeanElementTheorySgp4: "MEAN_ELEMENT_THEORY_SGP4",
    } as const;
    export type MeanElementTheory = (typeof MeanElementTheory)[keyof typeof MeanElementTheory];
}
