// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

export interface Orbit {
    /** Orbit Mean Elements data, analogous to the Orbit Mean Elements Message in CCSDS 502.0-B-3 */
    orbitMeanElements?: Lattice.OrbitMeanElements | undefined;
}
