// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Metadata about entity overrides present.
 */
export interface Overrides {
    override?: Lattice.Override[] | undefined;
}
