// This file was auto-generated by Fern from our API Definition.

/**
 * Owner designates the entity responsible for writes of task data.
 */
export interface Owner {
    /** Entity ID of the owner. */
    entityId?: string | undefined;
}
