// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

export interface PathMetadata {
    content_identifier: Lattice.ContentIdentifier;
    size_bytes: number;
    last_updated_at: string;
    expiry_time?: string | undefined;
}
