// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Individual payload configuration.
 */
export interface Payload {
    config?: Lattice.PayloadConfiguration | undefined;
}
