// This file was auto-generated by Fern from our API Definition.

export interface PayloadConfiguration {
    /**
     * Identifying ID for the capability.
     *  This ID may be used multiple times to represent payloads that are the same capability but have different operational states
     */
    capabilityId?: string | undefined;
    /** The number of payloads currently available in the configuration. */
    quantity?: number | undefined;
    /** The target environments the configuration is effective against. */
    effectiveEnvironment?: PayloadConfiguration.EffectiveEnvironment.Item[] | undefined;
    /** The operational state of this payload. */
    payloadOperationalState?: PayloadConfiguration.PayloadOperationalState | undefined;
    /** A human readable description of the payload */
    payloadDescription?: string | undefined;
}

export namespace PayloadConfiguration {
    export type EffectiveEnvironment = EffectiveEnvironment.Item[];

    export namespace EffectiveEnvironment {
        export const Item = {
            EnvironmentUnknown: "ENVIRONMENT_UNKNOWN",
            EnvironmentAir: "ENVIRONMENT_AIR",
            EnvironmentSurface: "ENVIRONMENT_SURFACE",
            EnvironmentSubSurface: "ENVIRONMENT_SUB_SURFACE",
            EnvironmentLand: "ENVIRONMENT_LAND",
            EnvironmentSpace: "ENVIRONMENT_SPACE",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }

    /** The operational state of this payload. */
    export const PayloadOperationalState = {
        PayloadOperationalStateInvalid: "PAYLOAD_OPERATIONAL_STATE_INVALID",
        PayloadOperationalStateOff: "PAYLOAD_OPERATIONAL_STATE_OFF",
        PayloadOperationalStateNonOperational: "PAYLOAD_OPERATIONAL_STATE_NON_OPERATIONAL",
        PayloadOperationalStateDegraded: "PAYLOAD_OPERATIONAL_STATE_DEGRADED",
        PayloadOperationalStateOperational: "PAYLOAD_OPERATIONAL_STATE_OPERATIONAL",
        PayloadOperationalStateOutOfService: "PAYLOAD_OPERATIONAL_STATE_OUT_OF_SERVICE",
        PayloadOperationalStateUnknown: "PAYLOAD_OPERATIONAL_STATE_UNKNOWN",
    } as const;
    export type PayloadOperationalState = (typeof PayloadOperationalState)[keyof typeof PayloadOperationalState];
}
