// This file was auto-generated by Fern from our API Definition.

export interface PrimaryCorrelation {
    /** The secondary entity IDs part of this correlation. */
    secondaryEntityIds?: string[] | undefined;
}
