// This file was auto-generated by Fern from our API Definition.

export interface Quaternion {
    /** x, y, z are vector portion, w is scalar */
    x?: number | undefined;
    y?: number | undefined;
    z?: number | undefined;
    w?: number | undefined;
}
