// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Range rings allow visual assessment of map distance at varying zoom levels.
 */
export interface RangeRings {
    /** The minimum range ring distance, specified in meters. */
    minDistanceM?: number | undefined;
    /** The maximum range ring distance, specified in meters. */
    maxDistanceM?: number | undefined;
    /** The count of range rings. */
    ringCount?: number | undefined;
    /** The color of range rings, specified in hex string. */
    ringLineColor?: Lattice.Color | undefined;
}
