// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Describes the relationships associated with this task: the system assigned to
 *  execute the task, and the parent task, if one exists.
 */
export interface Relations {
    /** The system, user, or team assigned to the task. */
    assignee?: Lattice.Principal | undefined;
    /** Identifies the parent task if the task is a sub-task. */
    parentTaskId?: string | undefined;
}
