// This file was auto-generated by Fern from our API Definition.

/**
 * Any metadata associated with the replication of a task.
 */
export interface Replication {
    /** The time by which this task should be assumed to be stale. */
    staleTime?: string | undefined;
}
