// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Sets an optional try strategy for tasks. Use this option to control how Lattice attempts to retry delivery of tasks to assets with intermittent access or network connectivity to your environment.
 */
export interface RetryStrategy {
    fixedRetryStrategy?: Lattice.FixedRetry | undefined;
}
