// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Represents RF configurations supported on this sensor.
 */
export interface RfConfiguration {
    /** Frequency ranges that are available for this sensor. */
    frequencyRangeHz?: Lattice.FrequencyRange[] | undefined;
    /** Bandwidth ranges that are available for this sensor. */
    bandwidthRangeHz?: Lattice.BandwidthRange[] | undefined;
}
