// This file was auto-generated by Fern from our API Definition.

export interface RouteDetails {
    /** Free form text giving the name of the entity's destination */
    destinationName?: string | undefined;
    /** Estimated time of arrival at destination */
    estimatedArrivalTime?: string | undefined;
}
