// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Schedules associated with this entity
 */
export interface Schedules {
    schedules?: Lattice.Schedule[] | undefined;
}
