// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * List of sensors available for an entity.
 */
export interface Sensors {
    sensors?: Lattice.Sensor[] | undefined;
}
