// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Represents the state of supplies associated with an entity (available but not in condition to use immediately)
 */
export interface Supplies {
    munitions?: Lattice.Munition[] | undefined;
    fuel?: Lattice.Fuel[] | undefined;
}
