// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * The target prioritization associated with an entity.
 */
export interface TargetPriority {
    /** Describes the target priority in relation to high value target lists. */
    highValueTarget?: Lattice.HighValueTarget | undefined;
    /** Describes whether the entity should be treated as a threat */
    threat?: Lattice.Threat | undefined;
}
