// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Error information associated with a task.
 *
 *  TaskError contains structured error details, including an error code, a human-readable
 *  message, and optional extended error information. This structure is used when a task
 *  encounters problems during its lifecycle.
 */
export interface TaskError {
    /** Error code for task error. */
    code?: TaskError.Code | undefined;
    /** Descriptive human-readable string regarding this error. */
    message?: string | undefined;
    /** Any additional details regarding this error. */
    errorDetails?: Lattice.GoogleProtobufAny | undefined;
}

export namespace TaskError {
    /** Error code for task error. */
    export const Code = {
        ErrorCodeInvalid: "ERROR_CODE_INVALID",
        ErrorCodeCancelled: "ERROR_CODE_CANCELLED",
        ErrorCodeRejected: "ERROR_CODE_REJECTED",
        ErrorCodeTimeout: "ERROR_CODE_TIMEOUT",
        ErrorCodeFailed: "ERROR_CODE_FAILED",
    } as const;
    export type Code = (typeof Code)[keyof typeof Code];
}
