// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Catalog of supported tasks.
 */
export interface TaskCatalog {
    taskDefinitions?: Lattice.TaskDefinition[] | undefined;
}
