// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Response containing tasks that match the query criteria.
 *
 * This message returns a list of Task objects that satisfy the filter conditions
 * specified in the request. When there are more matching tasks than can be returned
 * in a single response, a page_token is provided to retrieve the next batch in
 * a subsequent request. An empty tasks list with no page_token indicates that
 * there are no more matching tasks.
 */
export interface TaskQueryResults {
    tasks?: Lattice.Task[] | undefined;
    /**
     * Incomplete results can be detected by a non-empty nextPageToken field in the query results. In order to retrieve
     * the next page, perform the exact same request as previously and append a pageToken field with the value of
     * nextPageToken from the previous page. A new nextPageToken is provided on the following pages until all the
     * results are retrieved.
     */
    nextPageToken?: string | undefined;
}
