// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * A task represents a structured unit of work that can be assigned to an agent for execution.
 *
 *  Tasks are the fundamental building blocks of work assignment in the Lattice.
 *  Each task has a unique identifier, a specification defining what needs to be done,
 *  status information tracking its progress, and various metadata facilitating its lifecycle management.
 *
 *  Tasks can be related to each other, through parent-child relationships, assigned to
 *  specific agents, and tracked through a well-defined state machine from creation to completion.
 *  They support rich status reporting, including progress updates, error handling, and results.
 */
export interface Task {
    /** Version of this task. */
    version?: Lattice.TaskVersion | undefined;
    /** DEPRECATED: Human readable display name for this task, should be short (<100 chars). */
    displayName?: string | undefined;
    /** The path for the Protobuf task definition, and the complete task data. */
    specification?: Lattice.GoogleProtobufAny | undefined;
    /** Records who created this task. This field will not change after the task has been created. */
    createdBy?: Lattice.Principal | undefined;
    /** Records who updated this task last. */
    lastUpdatedBy?: Lattice.Principal | undefined;
    /** Records the time of last update. */
    lastUpdateTime?: string | undefined;
    /** The status of this task. */
    status?: Lattice.TaskStatus | undefined;
    /** If the task has been scheduled to execute, what time it should execute at. */
    scheduledTime?: string | undefined;
    /** Any related Tasks associated with this, typically includes an assignee for this task and/or a parent. */
    relations?: Lattice.Relations | undefined;
    /** Longer, free form human readable description of this task */
    description?: string | undefined;
    /**
     * If set, execution of this task is managed elsewhere, not by Task Manager.
     *  In other words, task manager will not attempt to update the assigned agent with execution instructions.
     */
    isExecutedElsewhere?: boolean | undefined;
    /** Time of task creation. */
    createTime?: string | undefined;
    /** If populated, designates this to be a replicated task. */
    replication?: Lattice.Replication | undefined;
    /**
     * If populated, indicates an initial set of entities that can be used to execute an entity aware task
     *  For example, an entity Objective, an entity Keep In Zone, etc.
     *  These will not be updated during execution. If a taskable agent needs continuous updates on the entities from the
     *  COP, can call entity-manager, or use an AlternateId escape hatch.
     */
    initialEntities?: Lattice.TaskEntity[] | undefined;
    /**
     * The networked owner of this task. It is used to ensure that linear writes occur on the node responsible
     *  for replication of task data to other nodes running Task Manager.
     */
    owner?: Lattice.Owner | undefined;
    /** Sets an optional try strategy for tasks. Use this option to control how Lattice attempts to retry delivery of tasks to assets with intermittent access or network connectivity to your environment. */
    retryStrategy?: Lattice.RetryStrategy | undefined;
    /** The current delivery state of a task. */
    deliveryState?: Lattice.DeliveryState | undefined;
}
