// This file was auto-generated by Fern from our API Definition.

/**
 * Defines a supported task by the task specification URL of its "Any" type.
 */
export interface TaskDefinition {
    /** Url path must be prefixed with `type.googleapis.com/`. */
    taskSpecificationUrl?: string | undefined;
}
