// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../index.js";

/**
 * Comprehensive status information for a task at a given point in time.
 *
 *  TaskStatus contains all status-related information for a task, including its current state,
 *  any error conditions, progress details, results, timing information, and resource allocations.
 *  This object evolves throughout a task's lifecycle, providing increasing detail as the task
 *  progresses from creation through execution to completion.
 */
export interface TaskStatus {
    /** Status of the task. */
    status?: TaskStatus.Status | undefined;
    /** Any errors associated with the task. */
    taskError?: Lattice.TaskError | undefined;
    /** Any incremental progress on the task, should be from the tasks/v* /progress folder. */
    progress?: Lattice.GoogleProtobufAny | undefined;
    /** Any final result of the task, should be from tasks/v* /result folder. */
    result?: Lattice.GoogleProtobufAny | undefined;
    /** Time the task began execution, may not be known even for executing Tasks. */
    startTime?: string | undefined;
    /** Any estimate for how the task will progress, should be from tasks/v* /estimates folder. */
    estimate?: Lattice.GoogleProtobufAny | undefined;
    /** Any allocated agents of the task. */
    allocation?: Lattice.Allocation | undefined;
}

export namespace TaskStatus {
    /** Status of the task. */
    export const Status = {
        StatusInvalid: "STATUS_INVALID",
        StatusCreated: "STATUS_CREATED",
        StatusScheduledInManager: "STATUS_SCHEDULED_IN_MANAGER",
        StatusSent: "STATUS_SENT",
        StatusMachineReceipt: "STATUS_MACHINE_RECEIPT",
        StatusAck: "STATUS_ACK",
        StatusWilco: "STATUS_WILCO",
        StatusExecuting: "STATUS_EXECUTING",
        StatusWaitingForUpdate: "STATUS_WAITING_FOR_UPDATE",
        StatusDoneOk: "STATUS_DONE_OK",
        StatusDoneNotOk: "STATUS_DONE_NOT_OK",
        StatusReplaced: "STATUS_REPLACED",
        StatusCancelRequested: "STATUS_CANCEL_REQUESTED",
        StatusCompleteRequested: "STATUS_COMPLETE_REQUESTED",
        StatusVersionRejected: "STATUS_VERSION_REJECTED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
