// This file was auto-generated by Fern from our API Definition.

/**
 * Describes whether an entity is a threat or not.
 */
export interface Threat {
    /** Indicates that the entity has been determined to be a threat. */
    isThreat?: boolean | undefined;
}
