// This file was auto-generated by Fern from our API Definition.

export interface TleParameters {
    /** Integer specifying TLE ephemeris type */
    ephemerisType?: number | undefined;
    /** User-defined free-text message classification/caveats of this TLE */
    classificationType?: string | undefined;
    /** Norad catalog number: integer up to nine digits. */
    noradCatId?: number | undefined;
    elementSetNo?: number | undefined;
    /** Optional: revolution number */
    revAtEpoch?: number | undefined;
    /** Drag parameter for SGP-4 in units 1 / Earth radii */
    bstar?: number | undefined;
    /** Drag parameter for SGP4-XP in units m^2 / kg */
    bterm?: number | undefined;
    /** First time derivative of mean motion in rev / day^2 */
    meanMotionDot?: number | undefined;
    /** Second time derivative of mean motion in rev / day^3. For use with SGP or PPT3. */
    meanMotionDdot?: number | undefined;
    /** Solar radiation pressure coefficient A_gamma / m in m^2 / kg. For use with SGP4-XP. */
    agom?: number | undefined;
}
