// This file was auto-generated by Fern from our API Definition.

/**
 * symmetric 2d matrix only representing the upper right triangle, useful for
 *  covariance matrices
 */
export interface TMat2 {
    mxx?: number | undefined;
    mxy?: number | undefined;
    myy?: number | undefined;
}
