// This file was auto-generated by Fern from our API Definition.

/**
 * A User Principal representing a human.
 */
export interface User {
    /** The User ID associated with this User. */
    userId?: string | undefined;
}
