// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../../../index.js";

/**
 * The stream event response.
 */
export type StreamTasksResponse = Lattice.StreamTasksResponse.Heartbeat | Lattice.StreamTasksResponse.TaskEvent;

export namespace StreamTasksResponse {
    export interface Heartbeat extends Lattice.StreamHeartbeat {
        event: "heartbeat";
    }

    export interface TaskEvent extends Lattice.TaskStreamEvent {
        event: "task_event";
    }
}
