// This file was auto-generated by Fern from our API Definition.

import type * as Lattice from "../../../index.js";

/**
 * The stream event response.
 */
export type StreamAsAgentResponse =
    | Lattice.StreamAsAgentResponse.Heartbeat
    | Lattice.StreamAsAgentResponse.AgentRequest;

export namespace StreamAsAgentResponse {
    export interface Heartbeat extends Lattice.StreamHeartbeat {
        event: "heartbeat";
    }

    export interface AgentRequest extends Lattice.AgentStreamEvent {
        event: "agent_request";
    }
}
