// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetTokenRequest {
    /** The client identifier */
    client_id?: string;
    /** The client secret */
    client_secret?: string;
}
