// This file was auto-generated by Fern from our API Definition.

import type { MockServer } from "../mock-server/MockServer";

export function mockOAuth(server: MockServer): void {
    const rawRequestBody = {
        grant_type: "client_credentials",
        client_id: "test_client_id",
        client_secret: "test_client_secret",
    };
    const rawResponseBody = {
        access_token: "access_token",
        token_type: "Bearer",
        expires_in: 3600,
        refresh_expires_in: 1,
        "not-before-policy": 1,
        scope: "scope",
    };
    server
        .mockEndpoint()
        .post("/api/v1/oauth/token")
        .formUrlEncodedBody(rawRequestBody)
        .respondWith()
        .statusCode(200)
        .jsonBody(rawResponseBody)
        .build();
}
