// This file was auto-generated by Fern from our API Definition.

import { EntitiesClient } from "./api/resources/entities/client/Client.js";
import { OauthClient } from "./api/resources/oauth/client/Client.js";
import { ObjectsClient } from "./api/resources/objects/client/Client.js";
import { TasksClient } from "./api/resources/tasks/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace LatticeClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class LatticeClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<LatticeClient.Options>;
    protected _entities: EntitiesClient | undefined;
    protected _tasks: TasksClient | undefined;
    protected _objects: ObjectsClient | undefined;
    protected _oauth: OauthClient | undefined;

    constructor(options: LatticeClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get entities(): EntitiesClient {
        return (this._entities ??= new EntitiesClient(this._options));
    }

    public get tasks(): TasksClient {
        return (this._tasks ??= new TasksClient(this._options));
    }

    public get objects(): ObjectsClient {
        return (this._objects ??= new ObjectsClient(this._options));
    }

    public get oauth(): OauthClient {
        return (this._oauth ??= new OauthClient(this._options));
    }
}
