// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListObjectsRequest {
    /** Filters the objects based on the specified prefix path. If no path is specified, all objects are returned. */
    prefix?: string;
    /** Sets the age for the oldest objects to query across the environment. */
    sinceTimestamp?: string;
    /** Base64 and URL-encoded cursor returned by the service to continue paging. */
    pageToken?: string;
    /** Lists objects across all environment nodes in a Lattice Mesh. */
    allObjectsInMesh?: boolean;
    /** Sets the maximum number of items that should be returned on a single page. */
    maxPageSize?: number;
}
